- name: Install packages
  hosts: localhost
  tasks:

    - name: Install ansible dnf
      ansible.builtin.shell: |
        dnf install -y python3-dnf
        exit $(python -c "import dnf")
      register: ec
      failed_when: ec.rc != 0
      changed_when: false

    - name: Install new packages
      ansible.builtin.dnf:
        name:
          - bootc
          - distrobox
          - hwinfo
          - fswatch
          # - gnome-session-xsession
          - htop
          - ifuse
          - inxi
          - kitty
          - libva-utils
          - libtree-sitter
          - lm_sensors
          - material-icons-fonts
          - nvidia-vaapi-driver
          - opencl-filesystem
          - plymouth-theme-spinfinity
          - samba
          - vdpauinfo
          - xclip
          # - xorg-x11-server-devel
          # - setxkbmap
          # - xhost
          # - xmodmap
          # - xorg-x11-xauth
          # - xorg-x11-xinit
          # - xrdb
          - zsh
        state: present

    - name: Remove packages
      ansible.builtin.dnf:
        name:
          - firefox
          # - mesa-va-drivers
          - firefox-langpacks
          - virtualbox-guest-additions # because of the dependencies on the kernel package
        state: absent

    - name: Autoremove unneeded packages installed as dependencies
      ansible.builtin.dnf:
        autoremove: true

    - name: Install longterm kernel
      ansible.builtin.shell: |
        set -oeux pipefail
        {{ buildroot }}/scripts/kernel-installer.sh
        echo $(rpm -q --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}' kernel-longterm)
      args:
        executable: /bin/bash
      register: kernel_query
      failed_when: kernel_query.rc != 0
      changed_when: false
      # when: 0 > 1

    - name: Get kernel version
      ansible.builtin.shell: |
        # TODO: Get the kernel version from the /lib/modules folder
        echo $(ls /usr/lib/modules/)
        # echo $(rpm -q --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}' kernel)
      register: kernel_query
      failed_when: kernel_query.rc != 0
      changed_when: false
      # when: 0 > 1

    - name: Set kernel version
      ansible.builtin.set_fact:
        kernel_version: "{{ kernel_query.stdout }}"
      # when: 0 > 1

    - name: Install Nvidia drivers
      ansible.builtin.shell: |
        set -oeux pipefail
        {{ buildroot }}/scripts/nvidia-installer.sh
      register: result
      failed_when: result.rc != 0
      changed_when: false
      # when: 0 > 1

    - name: Install Nvidia kernel modules
      ansible.builtin.copy:
        src: "/tmp/builder/nvidia/{{ kernel_version }}/{{ item }}"
        dest: "/usr/lib/modules/{{ kernel_version }}/kernel/drivers/video/"
        mode: "0755"
      loop:
        - nvidia-drm.ko
        - nvidia-modeset.ko
        - nvidia-peermem.ko
        - nvidia-uvm.ko
        - nvidia.ko

    - name: Kernel depmod
      ansible.builtin.shell: |
        depmod {{ kernel_version }}
      register: result
      failed_when: result.rc != 0
      changed_when: false

    - name: Cleanup container
      ansible.builtin.shell: |
        rm -rf /tmp/*
        rm -rf /var/*
        dnf -y clean all
        exit 0
      register: result
      failed_when: result.rc != 0
      changed_when: false
