name: Build All
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 7 * * *'  # 7 am everyday
  workflow_dispatch:

jobs:

  # build oci container image
  job-build-system:
    permissions:
      contents: write
      packages: write
      id-token: write
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    uses: ./.github/workflows/build-system.yml
    secrets: inherit

  # remove old images
  job-clean-images:
    needs: job-build-system
    uses: ./.github/workflows/cleanup.yml
    secrets: inherit
