name: Build All

on:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 7 * * *'  # 7 am everyday
    #- cron: '0 12 * * 4' # Runs at 12:00 only on Thursday.
  workflow_dispatch:
#
jobs:
  job-build-akmods:
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
    uses: ./.github/workflows/build-akmods.yml
